# A string used to distinguish different Supabase projects on the same host
project_id = "academy-ai"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public"]
# Extra schemas to add to the search_path
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a view, table, or stored procedure
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323
# External URL of the API server that frontend connects to
api_url = "http://localhost"

[inbucket]
# Port to use for the email testing server web interface
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website
site_url = "http://localhost:3000"
# Disable signup
enable_signup = true
# Allow/disallow new user signups to your project
enable_anonymous_sign_ins = false

[auth.email]
# Allow/disallow new user signups via email
enable_signup = true
# If enabled, a user will be required to confirm any email change
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in
enable_confirmations = false

[auth.external.google]
enabled = false
